services:
  dev_container:
    build:
      context: .
      target: develop
      additional_contexts:
        - vscode=./devContainer/vscode_context
      args:
         UID: ${HOST_UID} 
         GID: ${HOST_GID}
         UNAME: ${HOST_UNAME}
         BLA: "blub"
    depends_on:
      - dbg_web_server
    volumes:
      - ../../webapp:/home/${HOST_UNAME}/workspace/webapp
    network_mode: bridge
    ports:
      - "9222"
    stdin_open: true
    tty: true
    container_name: dev_container
  dbg_web_server:
    build:
      context: .
      target: debug
    volumes:
      - ../../webapp:/usr/src/app
      - ../../certs/private:/etc/ssl/private/websrv
    network_mode: bridge
    ports:
     - "8080:5000"
    container_name: dbg_web_server_container
  # prod_web_server:
  #   build:
  #    context: .
  #    target: prod
  #   volumes:
  #     - ../../websapp:/usr/src/app
  #     - ../../certs/private:/etc/ssl/private/websrv
  #   network_mode: bridge
  #   ports:
  #     - "8081:5000"
  #   container_name: prod_web_server_container